happy:
  code:
    swagger:
      base-package: cool.happycoding.code.mybatis.sample
      enable: true
      group: happy-code-starter-mybatis-sample
      title: mybatis组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy
    user:
      default-user-id: 999
      default-user-name: lanlanhappy
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    cool.happycoding.code.mybatis.sample.domain.mapper: debug