happy:
  code:
    swagger:
      base-package: cool.happycoding.code.user.sample
      enable: true
      group: happy-code-starter-user-sample
      title: user组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy
    user:
      default-user-id: 999
      default-user-name: lanlanhappy
