CREATE TABLE IF NOT EXISTS  h2user (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
    name VARCHAR(30) NULL DEFAULT NULL,
	age INT(11) NULL DEFAULT NULL,
    gender VARCHAR(16) NULL DEFAULT NULL,
	addr VARCHAR(255) NULL DEFAULT NULL,
	salary DECIMAL(10,2) NULL DEFAULT NULL,
	remark VARCHAR(30) NULL DEFAULT NULL,
    created_by VARCHAR(30) NULL DEFAULT NULL ,
    created_by_id VARCHAR(30) NULL DEFAULT NULL ,
    created_time DATETIME NULL DEFAULT NULL,
    updated_by VARCHAR(30) NULL DEFAULT NULL ,
    updated_by_id VARCHAR(30) NULL DEFAULT NULL ,
    updated_time DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (id)
);