happy:
  code:
    swagger:
      base-package: cool.happycoding.validator.sample
      enable: true
      group: happy-code-starter-validator-sample
      title: web组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy