happy:
  code:
    swagger:
      base-package: cool.happycoding.code.stream.mq.sample
      enable: true
      group: happy-code-starter-stream-mq-sample
      title: user组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy
server:
  port: 8083
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        output:
          destination: stream-mq-output
          content-type: application/json
        input:
          destination: stream-mq-output
          content-type: application/json
          group: input-group
