happy:
  code:
    swagger:
      base-package: cool.happycoding.code.mq.sample
      enable: true
      group: happy-code-starter-mq-sample
      title: user组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy
rocketmq:
  name-server: localhost:9876
  producer:
    group: my-group1
    send-message-timeout: 30000
server:
  port: 8081
